version: '3.8'

services:
## Apache Spark + Notebook
  spark:
    platform: linux/x86_64
    image: alexmerced/spark35notebook:latest
    ports: 
      - 8080:8080  # Master Web UI
      - 7077:7077  # Master Port
      - 8888:8888  # Notebook
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin #minio username
      - AWS_SECRET_ACCESS_KEY=password #minio password
    container_name: spark-iceberg
    networks:
        dremio-iceberg:
## Dremio Lakehouse Platform
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio-iceberg
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      dremio-iceberg:
## Minio Object Storage
  minio:
    image: minio/minio
    container_name: minio-iceberg
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    command: server /data --console-address ":9001"
    networks:
        dremio-iceberg:
## Nessie Iceberg Catalog
  nessie:
    image: projectnessie/nessie
    container_name: nessie-iceberg
    ports:
      - "19120:19120"
    networks:
        dremio-iceberg:

networks:
  dremio-iceberg: